highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "Mr. U"
markdown: kramdown

author: "Mr. U"

gems:
  - jekyll-feed

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Qingxinge
    class: fa fa-film
    href: http://misteru.github.io
  - title: Subscribe
    class: fa fa-rss
    href: /feed.xml

